version: '2'
services:
  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator:0.7.3
    ports:
     - "127.0.0.1:9010:9010"
     - "127.0.0.1:9020:9020"
    environment:
     - SPANNER_EMULATOR_HOST=localhost:9010
